---
title: "A Replication Study"
subtitle: "Bayesian Inference for Agreement Measures"
author: 
- Lingjuan Qi\inst{1}
- Matthew Aaron Looney\inst{2}
institute: |
  | \inst{1} Department of Mechanical Engineering
  | \inst{2} Department of Applied Economics
  | Texas Tech University
date: "July 3, 2018"
output:
  beamer_presentation:
    fig_caption: yes
    fonttheme: structurebold
    theme: Montpellier
    toc: no
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

cat("\014")
rm(list=ls())

```


# Goals of this Research

## Replicate the results of:

  * Bayesian Inference for Agreement Measures.

    - By: Ignacio Vidal and Mário de Castro.

    - Journal of biopharmaceutical statistics, 2016 p. 809-823.


## The main ideas behind the paper:

Methods for assessing agreement between a set of paired observations has been well studied in the literature. Most of the studies have focused on using a frequentist approach to calculate several measures of measurement agreement.



## A Motivating Example with Real World Data:

Renal lithiasis (Kidney Stones) can be defined as the consequence of an alteration of the normal crystallization conditions of urine in the urinary tract. In a healthy individual, during the residence time of urine in the urinary tract, crystals either do not form or are so small they are eliminated uneventfully. Clinicians often employ diagnostic imaging techniques to quantify the size, shape, and likelihood the stones will pass through the system without incident.

## A Motivating Example with Real World Data:

There are two main imaging tools used by clinicians to assess renal lithiasis:

* High-speed or dual energy Computerized Tomography (CT).

* Intravenous Urography, which involves injecting dye into an arm vein and taking X-rays (intravenous pyelogram).



## Assessing Agreement Between Measurements:

* A way to assess agreement between two random variables X and Y is the mean squared deviation (MSD).

$$MSD = E\left[ {{{(X - Y)}^2}} \right] = {({\mu _x} - {\mu _y})^2} + \sigma _x^2 + \sigma _y^2 - 2{\sigma _{xy}}$$

## Assessing Agreement Between Measurements:

* Another measure of agreement between two random variables is the Concordance Correlation Coefficient ( CCC ).

$${\rho _c} = 1 - {{MSD} \over {MSD{|_{{\sigma _{xy}} = 0}}}} = {{2{\sigma _{XY}}} \over {{{({\mu _X} - {\mu _Y})}^2} + \sigma _X^2 + \sigma _Y^2}}$$


# The Bayesian Model



## Likelihood


## Prior


## Posterior



