---
title: "A Replication Study on:"
subtitle: "Bayesian inference for agreement measures"
author:
- "Lingjuan Qi"
- "Matthew Aaron Looney"
date: "June 25, 2018"

output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: no
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
    
abstract: "Insert Abstract Here"
    
header-includes:
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
- \usepackage{amssymb,amsmath}
- \usepackage{dcolumn}
- \usepackage{setspace}
- \usepackage{mathrsfs}
- \usepackage{eso-pic,graphicx,transparent}

bibliography: paper_projectBib.bib
csl: computational-economics.csl
link-citations: true
fontsize: 10pt
geometry: margin = 1.25in

---

```{r, echo=F, message=F, warning=F}

# Housekeeping ----------------------------------------------------------------

rm(list= ls())
cat("\014")

library(summarytools)


```

```{r, echo=F, message=F, warning=F}

# Import Data -----------------------------------------------------------------

IPIA_Data <- read.csv("/Users/malooney/Google Drive/digitalLibrary/*Decesion_Theory/Decision_Theory/data/IPIA_Data.csv")

```

\newpage

---

# Introduction

\onehalfspacing




```{r, echo=F}

# mean(IPIA_Data$Urography)
# sd(IPIA_Data$Urography)
# min(IPIA_Data$Urography)
# max(IPIA_Data$Urography)
# 
# 
# mean(IPIA_Data$Tomography)
# sd(IPIA_Data$Tomography)
# min(IPIA_Data$Tomography)
# max(IPIA_Data$Tomography)

```

```{r, echo=F, results='asis'}

# Problem 3.c freq table ------------------------------------------------------
diff <- abs(IPIA_Data$Urography- IPIA_Data$Tomography)

freq(as.vector(diff), report.nas= F, style= "rmarkdown",
     omit.headings =T)
```

```{r, echo=F, results='asis'}

descr(IPIA_Data[,-1], style = "rmarkdown" , transpose = T, 
      split.tables = 100, omit.headings = T)


```

```{r, echo=F, fig.height=4}

par(mfrow= c(1, 2), ps= 10, cex= 0.55, cex.main= 1.5)

hist(IPIA_Data$Tomography, 
     prob = TRUE, 
     col= rgb(234/255, 51/255, 35/255, alpha=0.25), 
     main= "Density plot of Tomography")

rug(IPIA_Data$Tomography)

lines(density(IPIA_Data$Tomography), col="red")

hist(IPIA_Data$Urography, 
     prob = TRUE, 
     col= rgb(117/255, 250/255, 76/255, alpha=0.25), 
     main= "Density plot of Urography", ylim= c(0, 0.035))

rug(IPIA_Data$Urography)

lines(density(IPIA_Data$Urography), col="green")

#legend(85, 0.026,  c("Tomography", "Urography"),
#       lty=c(1, 1), col=c("red","green"))

```
























---

# References: